#!/usr/bin/env bash

# Updates submodules and makes sure that sumodule submdules are at the
# correct version.

# Update each submodule to the most recent master version. There are
# multiple way to do this, currently this is my favorite.
git submodule foreach "git checkout master && git pull"

# Make sure that submodule submodules are at the correct version.
git submodule foreach "git submodule update --init --recursive"

# And we're done.
echo "$(tput setaf 5)Done!$(tput sgr0)"
