directory: ~/Music
library: ~/.local/share/beets/library.blb
import:
  move: yes
ui:
  color: yes
plugins:
  - web
  - fetchart
  - lastgenre
  - lastimport
  - thumbnails
  - mpdstats
  - mbsync
  - edit
  - acousticbrainz
  - discogs
  - chroma
lastfm:
  user: MaikuMori
mpd:
  host: /home/maiku/.local/share/mpd/socket
  port: 6600
smartplaylist:
  relative_to: ~/Music
  playlist_dir: ~/.local/share/mpd/playlists
  playlists:
    - name: all.m3u
      query: ''
